variables:
#  DOCKER_HOST: 'tcp://docker:2375/' # NOT WORK AS KEPLOY DON'T' CARE AND USE /var/docker/docker/sock...but not locally :\
  DOCKER_TLS_CERTDIR: '' #
  PHP_DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/php-s:1.0.0"
  DOCKER_CLI_IMAGE: docker:27.3.1-cli
  DOCKER_DIND_IMAGE: docker:27.3.1-dind
  DOCKER_DRIVER: overlay2

stages:
  - 📏 tests

keploy-test-job: # This job runs in the test stage.
#  image: ${DOCKER_CLI_IMAGE}
  image: ${DOCKER_CLI_IMAGE} # CLI
  stage: 📏 tests
  cache:
    key:
      files:
        - composer.lock
    paths:
      - vendor
      - public
      - node_modules
  services:
    - ${DOCKER_DIND_IMAGE}
  before_script:
    - apk add --update --no-cache sudo curl make
    - curl --silent --location "https://github.com/keploy/keploy/releases/download/v2.3.0-beta38/keploy_linux_amd64.tar.gz" | tar xz --overwrite -C /tmp
    - sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin/keploy
    - sudo mount -t debugfs debugfs /sys/kernel/debug
  script:
    - cd symfony/
    - docker ps -q --filter "name=keploy-v2" | grep -q . && docker stop keploy-v2 && docker rm -fv keploy-v2
    - make ENV=test NO_TTY=true keploy-test
  tags:
    - dockerbuilder # DIND with /var/lig/docker.sock shared
