api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/jsonld']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
